name: "Reusable workflow for SAST and SCA scans"

on:
  workflow_call:
    inputs:
      enable_sast:
        required: true
        type: boolean
        default: true
      enable_sca:
        required: true
        type: boolean
        default: true
      repo_url:
        required: true
        type: string
      branch_name:
        required: true
        type: string
    secrets:
      pat_token:
        required: false
      server:
        required: true

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Call Security Scan API for Selected Scans
        run: |
          private_token_param=""
          if [ ! -z "${{ secrets.pat_token }}" ]; then
            private_token_param="&private=${{ secrets.pat_token }}"
          fi
          response=$(curl -X GET \
            "${{ secrets.server }}/sastsca?sast=${{ inputs.enable_sast }}&sca=${{ inputs.enable_sca }}&repo=${{ inputs.repo_url }}&branch=${{ inputs.branch_name }}${private_token_param}")
          echo "API Response: $response"
          brief_sast=$(echo "$response" | jq -r '.["brief-sast"] // "null"')
          brief_sca=$(echo "$response" | jq -r '.["brief-sca"] // "null"')
          echo "brief_sast=$brief_sast" >> $GITHUB_ENV
          echo "brief_sca=$brief_sca" >> $GITHUB_ENV

      - name: Retrieve Results for SAST
        if: env.brief_sast != 'null'
        run: |
          for ((i=0; i<30; i++)); do
            response=$(curl -s -w "%{http_code}" "${{ secrets.server }}${{ env.brief_sast }}")
            http_code=${response: -3}
            if [ $http_code -eq 200 ]; then
              content=$(echo ${response} | head -c-4)
              echo "SAST Results:"
              echo "$content"
              break
            fi
            sleep 20
          done

      - name: Retrieve Results for SCA
        if: env.brief_sca != 'null'
        run: |
          for ((i=0; i<30; i++)); do
            response=$(curl -s -w "%{http_code}" "${{ secrets.server }}${{ env.brief_sca }}")
            http_code=${response: -3}
            if [ $http_code -eq 200 ]; then
              content=$(echo ${response} | head -c-4)
              echo "SCA Results:"
              echo "$content"
              break
            fi
            sleep 20
          done
